// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacancyProAPI.Models;

#nullable disable

namespace VacancyProAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231012095601_linkToVacances")]
    partial class linkToVacances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VacancyProAPI.Models.Activite", b =>
                {
                    b.Property<int>("IdActivite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivite"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JourDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JourFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VacancesIdVacances")
                        .HasColumnType("int");

                    b.HasKey("IdActivite");

                    b.HasIndex("VacancesIdVacances");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Vacances", b =>
                {
                    b.Property<int>("IdVacances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacances"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVacances");

                    b.ToTable("Vacances");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Activite", b =>
                {
                    b.HasOne("VacancyProAPI.Models.Vacances", null)
                        .WithMany("Activites")
                        .HasForeignKey("VacancesIdVacances");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Vacances", b =>
                {
                    b.Navigation("Activites");
                });
#pragma warning restore 612, 618
        }
    }
}
