// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacancyProAPI.Models;

#nullable disable

namespace VacancyProAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231018130448_lieuTovacances")]
    partial class lieuTovacances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VacancyProAPI.Models.Activite", b =>
                {
                    b.Property<int>("IdActivite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivite"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LieuxIdLieu")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdActivite");

                    b.HasIndex("LieuxIdLieu");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Lieux", b =>
                {
                    b.Property<int>("IdLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLieu"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLieu");

                    b.ToTable("Lieux");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Vacances", b =>
                {
                    b.Property<int>("IdVacances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacances"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LieuxIdLieu")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVacances");

                    b.HasIndex("LieuxIdLieu");

                    b.ToTable("Vacances");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Activite", b =>
                {
                    b.HasOne("VacancyProAPI.Models.Lieux", "Lieux")
                        .WithMany()
                        .HasForeignKey("LieuxIdLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lieux");
                });

            modelBuilder.Entity("VacancyProAPI.Models.Vacances", b =>
                {
                    b.HasOne("VacancyProAPI.Models.Lieux", "Lieux")
                        .WithMany()
                        .HasForeignKey("LieuxIdLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lieux");
                });
#pragma warning restore 612, 618
        }
    }
}
